### Расчет цены, несуществующий купон для скидки
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Расчет цены, существующий купон для скидки
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "SALE35"
}

### Неверный метод запроса
GET http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Неверные данные запроса
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
}

### Неверные данные запроса 2
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": -1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Неверные данные запроса 3
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "RU123456789"
}

### Неверные данные запроса 4
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 25,
  "taxNumber": "FR123456789"
}

### Покупка, несуществующий купон для скидки
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Покупка, существующий купон для скидки
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "SALE35",
  "paymentProcessor": "paypal"
}

### Неверный метод запроса
GET http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Неверные данные запроса
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
}

### Неверные данные запроса 2
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": -1,
  "taxNumber": "DE123456789",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Неверные данные запроса 3
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "RU123456789",
  "paymentProcessor": "paypal"
}

### Неверные данные запроса 4
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 25,
  "taxNumber": "FR123456789",
  "paymentProcessor": "paypal"
}

### Неверные данные запроса 5
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "FR123456789",
  "paymentProcessor": "sber"
}
