### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### No route found
GET http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Content violation 1
GET http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

### Content violation 2
GET http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": -1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}